### ISSUE TITLE
build SciLexer.dll with boost

### ISSUE THREAD

**Issue by Yaron10** [Yaron10/compare-plugin-Pavel-Nedev#12]
Hello @andrecool-68,

I've just seen the following thread you opened a while ago:
https://community.notepad-plus-plus.org/topic/17605/error-build-scilexer-dll-with-boost

Did you manage to successfully build it *with boost*?
If you did - may I ask you to modify the following files, build it and upload it here? 

scintilla/src/Editor.cxx
scintilla/win32/ScintillaWin.cxx

- Replace with the new files in https://github.com/notepad-plus-plus/notepad-plus-plus/ @d55350b

scintilla/include/Scintilla.h
scintilla/src/EditView.cxx
scintilla/src/Indicator.cxx
scintilla/src/Indicator.h

- Replace with the new files in https://github.com/notepad-plus-plus/notepad-plus-plus/ pull/8713/files

**I've added a space before `@d55350b` and `pull/8713/files` so that this issue is not referenced there.**

I've tried to build the DLL in various ways but, unfortunately, without successes.
I don't care about the signature as I'm using my own NPP.

I hope it wouldn't be much of a trouble for you.

BTW, thank you for opening the "A web link is not processed if it contains Cyrillic" issue.
The result is quite good.

.תודה רבה

**Comment by andrecool-68** [comment]
@Yaron10  Hello!
<https://github.com/notepad-plus-plus/notepad-plus-plus/ @ d55350b> This link is not working

**Comment by andrecool-68** [comment]
@Yaron10 
> I've tried to build the DLL in various ways but, unfortunately, without successes.

Is Visual Studio installed on your computer?

**Comment by Yaron10** [comment]
Hello @andrecool-68,

Thanks for replying.

Here is the correct link (with a space).
https://github.com/notepad-plus-plus/notepad-plus-plus/ commit/d55350b4b5db71889d0a92aabe5ae10d41c92507
("**Fix mouse cursor flicker while hovering**").

The second PR title is "**Bring blue underlined URLs back**".

> Is Visual Studio installed on your computer?

Yes, it is. But I've spent about an hour trying to build it and that's enough. :)
If you still have the required boost files and it's only modifying the 6 files I mentioned above - I'd appreciate it.

**Comment by andrecool-68** [comment]
@Yaron10 
I can't understand why I can't build the boost_1_70_0 library

**Comment by Yaron10** [comment]
Hello @andrecool-68,

Thank you for trying. I appreciate it.
I didn't mean to cause that much trouble.

I actually managed to build the boost_1_70_0 library.
The problem started with `nmake`.

Let's wait for the next NPP Release Candidate which should include a new DLL with boost.

Best regards.

**Comment by andrecool-68** [comment]
@Yaron10 
I had errors with paths))
Wait a bit ... it should work!

Test: [SciLexer-32-64.zip](https://github.com/Yaron10/compare-plugin-Pavel-Nedev/files/5095639/SciLexer-32-64.zip)

**Comment by Yaron10** [comment]
!כל הכבוד
:+1: :+1:  :+1: 
Thank you very much. Highly appreciated.

**Comment by andrecool-68** [comment]
@Yaron10 
My cheat sheet : [BUILD SciLexer.dll.txt](https://github.com/Yaron10/compare-plugin-Pavel-Nedev/files/5095965/BUILD.SciLexer.dll.txt)

**Comment by Yaron10** [comment]
Thank you for that too. :+1: 
I hope I won't need it soon. :)

.שוב תודה. מעריך מאוד

**Comment by andrecool-68** [comment]
@Yaron10 
> I don't care about the signature as I'm using my own NPP.

How can disable the nppGpgPub.asc signature for the release build of the project?

**Comment by Yaron10** [comment]
I was referring to the DLL signature.

You can comment the following lines in `ScintillaEditView.cpp`.
```
#ifndef _DEBUG
	SecurityGard securityGard;
	bool isOK = securityGard.checkModule(sciLexerPath, nm_scilexer);

	if (!isOK)
	{
		::MessageBox(NULL,
			TEXT("Authenticode check failed:\rsigning certificate or hash is not recognized"),
			TEXT("Library verification failed"),
			MB_OK | MB_ICONERROR);
		return nullptr;
	}
#endif // !_DEBUG
```

Or do you want to remove the EXE signature?
I've never tried it.
Is there a `nppGpgPub.asc` file?

**Comment by andrecool-68** [comment]
> Or do you want to remove the EXE signature?

Yes!

> Is there a `nppGpgPub.asc` file?

No)))

**Comment by Yaron10** [comment]
If you edit anything with a Resource Editor, shouldn't the signature be removed?

**Comment by andrecool-68** [comment]
Release build of Notepad ++ doesn't work without nppGpgPub.asc)))

What is the Resource Editor for?
If you have Visual Studio.

**Comment by Yaron10** [comment]
I thought a Resource Editor should remove the signature (which Visual Studio doesn't).

You seem to know much more about it than I do.
I really wish I was able to reciprocate and help you. I'm truly sorry I can't.

**Comment by andrecool-68** [comment]
Original build:
----

Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Users\Uzzer\Desktop\IE11-Windows6.1\Utilites\npp.7.8.6.bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Home Premium (32-bit) 
OS Build : 7601.0
Plugins : none

Nightly build (code comments):
----

Notepad++ v7.8.9   (32-bit)
Build time : Aug 19 2020 - 15:46:16
Path : C:\notepad-plus-plus-master\PowerEditor\bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Home Premium (32-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : none


Nightly build works!
But a new line appeared in the debug information:  `Current ANSI codepage : 1251`

**Comment by Yaron10** [comment]
> But a new line appeared in the debug information: Current ANSI codepage : 1251

This was added between v7.8.6 and v7.8.9.

> Nightly build works!

No signature? By commenting some parts of the code? - What parts?

**Comment by andrecool-68** [comment]
I have commented out the lines in ScintillaEditView.cpp that you told me))
Now everything works without a digital signature!

google translator does not understand me well))

**Comment by Yaron10** [comment]
Great!
I'm glad I *was* able to reciprocate and help you. :)

Why did you want to remove the signature from the EXE file?

**Comment by andrecool-68** [comment]
> Why did you want to remove the signature from the EXE file?

I thought I needed to delete it in the exe-file)))

**Comment by Yaron10** [comment]
So you wanted to use NPP with no-signature-DLL, correct?

Yes, you can not do that with the *original* EXE.
You have to comment those lines and use your *modified* EXE.

I'm glad it works for you.

**Comment by andrecool-68** [comment]
@Yaron10 
New cheat sheet
[boost_1_70_0-build-SciLexer.dll-x32-x64.txt](https://github.com/Yaron10/compare-plugin-Pavel-Nedev/files/5139017/boost_1_70_0-build-SciLexer.dll-x32-x64.txt)

**Comment by Yaron10** [comment]
@andrecool-68,

Thank you. I appreciate it.
I've messed up the project and I'd have to re-download it and start from scratch.
If and when I do that, I'll have a better look at your guide and maybe request your help.

If you still have the project on your machine, may I ask you to integrate the new file (scintilla/src/EditView.cxx) in https://github.com/notepad-plus-plus/notepad-plus-plus/ pull/8769?
(Scintilla fix for hovered indicators).

Obviously build it with the new files you replaced last time. :)

**Comment by andrecool-68** [comment]
@Yaron10 Create a zip archive with the files you want to replace and attach it to your message here.

**Comment by Yaron10** [comment]
[Modified Files.zip](https://github.com/Yaron10/compare-plugin-Pavel-Nedev/files/5139124/Modified.Files.zip).

Thank you.

**Comment by andrecool-68** [comment]
You can test :))
[SciLexer_TEST.zip](https://github.com/Yaron10/compare-plugin-Pavel-Nedev/files/5140023/SciLexer_TEST.zip)

**Comment by Yaron10** [comment]
Great job. :+1: 

Thank you. Much appreciated.
