### ISSUE TITLE
Help me find this menu "open file in browser"

### ISSUE THREAD

**Issue by Yaron10** [Yaron10/compare-plugin-Pavel-Nedev#16]
Hello @andrecool-68,

I've just seen your question in https://community.notepad-plus-plus.org/topic/20272/help-me-find-this-menu-open-file-in-browser.

Those entries are for the "Shortcut Mapper".

Best regards.

**Comment by Yaron10** [comment]
If you copy those entries to the `<Commands>` section, you'd see your localized strings in the menu.

![תמונה](https://user-images.githubusercontent.com/10229320/98157933-cca8f880-1ee2-11eb-8e9b-4273a53630f1.png)

**Comment by andrecool-68** [comment]
Hi Yaron!
I cut and pasted these lines elsewhere, everything works well. I do not understand why duplicate these lines.

![000](https://user-images.githubusercontent.com/3471892/98178582-a3e62a80-1f05-11eb-8b8a-d008848709a8.gif)

**Comment by Yaron10** [comment]
It has to do with https://github.com/notepad-plus-plus/notepad-plus-plus/ issues/8689.
(Different shortcut names in Shortcut Mapper table and menu).

I remember not understanding it when the issue was opened, but I didn't delve into it.

**Comment by andrecool-68** [comment]
Here we need more clear localization for everyone, and not invent a new mane bike))

**Comment by Yaron10** [comment]
:)
