### ISSUE TITLE
Window Menu and Dialog

### ISSUE THREAD

**Issue by Yaron10** [Yaron10/compare-plugin-Pavel-Nedev#20]
Hello @mere-human,

https://github.com/notepad-plus-plus/notepad-plus-plus/ issues/10354 (remove the space).

I'd like to thank you again for your kind willingness to work on it.
Reading Don's last reply, he still seems to misunderstand our suggestion.

If you're thinking of implementing it properly for your personal use, please let me know.
I'd integrate your code in my NPP build.

Best regards.

**Comment by mere-human** [comment]
Anyway, thanks for your ideas @Yaron10 !
You can also ping me via email, if you need to. It is publicly available in my profile.

**Comment by Yaron10** [comment]
:+1: 
Thank you. I do appreciate it.
