### ISSUE TITLE
קניית מסך מחשב ברוסיה

### ISSUE THREAD

**Issue by Yaron10** [Yaron10/compare-plugin-Pavel-Nedev#22]
@andrecool-68,

,שלום

:אני מעוניין לקנות אחד משני המסכים הבאים
https://www.asus.com/Displays-Desktops/Monitors/Eye-Care/VA229QSB/techspec
https://eu.aoc.com/en/products/monitors/22p2du/specification
.המסכים לא זמינים בארץ

?אתה מכיר חנות אמינה ברוסיה/אוקראינה שמציעה משלוחים לישראל

.אודה מאוד על עזרתך

**Comment by andrecool-68** [comment]
@Yaron10 נולדתי באוזבקיסטן, אני לא מכיר את החנויות ברוסיה ובאוקראינה. אני קונה רכיבי מחשב רק ב- KSP או Ivory.

**Comment by andrecool-68** [comment]
@Yaron10 החודש קניתי צג סמסונג בגודל 24 אינץ'
https://ksp.co.il/web/item/57892
מאוד מרוצה מהרכישה!

**Comment by Yaron10** [comment]
.תודה על התשובה

.נראה מסך מעולה
!תתחדש

What's Windows recommended/default scaling for that monitor? 100%?

מסכים גבוהים/רחבים לא נוחים לי. אני גם מעדיף מסך
.IPS

**Comment by andrecool-68** [comment]
@Yaron10  https://www.zap.co.il/models.aspx?sog=c-monitor&db435152=435154,3859499,435182,2553320

**Comment by Yaron10** [comment]
.תודה רבה
.מסכים גבוהים/רחבים לא נוחים לי

**Comment by andrecool-68** [comment]
@Yaron10  הקטלוג אומר, אין מוניטורים כאלה למכירה ברוסיה
https://market.yandex.ru/

**Comment by Yaron10** [comment]
שוב תודה. מעריך מאוד.

> What's Windows recommended/default scaling for that monitor? 100%?

ראית את השאלה הזו?
כתבתי באנגלית כי התצוגה פה היא LTR.

חשוב לי מאוד שקנה המידה בברירת מחדל יהיה 100% (DPI 96).
אתה יודע מה אמור להיות קנה המידה במסכים שציינתי?

**Comment by andrecool-68** [comment]
@Yaron10  If the default monitor resolution is 1920x1080, you need exactly 1920x1080.
And it doesn't matter how many inches the diagonal of the monitor is!
If the font in the browser is small for you, you only need to change the scaling of the browser itself.

**Comment by Yaron10** [comment]
I don't quite understand the subject.

I once had a 23.8 monitor 2560x1440 default resolution.
Windows recommended/default scaling was 125% and I didn't like it.

So how can I be sure that Windows recommended scaling should be 100% for a specific monitor?

Thanks again.

**Comment by andrecool-68** [comment]
@Yaron1 These are my screen settings, all default settings.
Samsung monitor 24"
100% is the default setting for any monitor. All other settings depend on the desire of the user and his vision.

![Безымянный](https://user-images.githubusercontent.com/3471892/137644712-78618a16-95f2-43e0-a28c-31ac8c0b50f8.png)

**Comment by Yaron10** [comment]
> 100% is the default setting for any monitor.

Are you sure? 

> I once had a 23.8 monitor 2560x1440 default resolution.
Windows recommended/default scaling was 125% and I didn't like it.

I'm positive about that.

Anyway, thanks again. I appreciate your kind help.

**Comment by andrecool-68** [comment]
@Yaron10 There are no exact recommendations, it all depends on the perception of the user's eyes. Монитор с очень высоким разрешением (2560x1440 и выше) актуален только для графических дизайнеров, а для обычного пользователя стоит приобрести монитор с разрешением 1920x1080

**Comment by Yaron10** [comment]
👍 
Thanks again.
